#ifndef _AUTOUPDATE_STRING_TABLE_T_
#define _AUTOUPDATE_STRING_TABLE_T_

	#define K_HOME_PAGE					"http://jx.gameflier.com"
	#define K_URL_COMPANY				"http://jx.gameflier.com"
	#define K_JXONLINE_FILE_NAME_0		"fsonline_T"
	#define K_JXONLINE_FILE_NAME_1		"fsonline_T.exe"
	#define K_GAME_FILE_NAME_0			"game_T"
	#define K_GAME_FILE_NAME_1			"game_T.exe"

	#define U_TOTAL_PROGRESS			"總體更新進度"
	#define U_CURRENT_FILE_PROGRESS		"當前更新文件"
	#define U_CANCEL_UPDATE				"取消升級..."
	#define U_CONNECTING_SERVER			"正在連接伺服器..."
	#define U_VERIFY_ACCOUNT			"正在進行用戶校驗..."
	#define U_LOADING_UPDATE_INFO		"正在下載更新資訊..."
	#define U_DOWNLOADING_FILE			"正在下載文件..."
	#define U_FILE_DOWNLOADING_STATUS	"%s --- %d KB(%d KB)"
	#define U_UPDATE_SYSTEM				"正在更新系統..."
	#define U_UPDATE_FINISH				"升級完成..."
	#define U_NEEDLESS_UPDATE			"已經是最新版本，不需要升級。"
	#define U_LOADICON_ERR				"LoadIcon(IDR_MAINFRAME) 出錯"
	#define U_LOAD_DLL					"調入動態庫'"
	#define U_GET_FUN_ADDRESS			"取得函數位址'"
	#define U_RELEASE_MODULE			"釋放模組'"
	#define U_TAIL_ERROR				"'出錯"
	#define U_SELECT_FOLDER				"瀏覽檔夾"
	#define U_AUTOUPDATE_SITE			"自動升級站點%d"
	#define U_ANALYSE_ADDRESS_ERR		"位址解析出錯！"
	#define U_ANALYSE_ADDRESS_ERR_2		"下載服務狀態檔時，解析位址出錯！"
	#define U_DOWNLOAD_FOLDER_LIST_FILE	"正在下載目錄列表檔..."
	#define U_DOWNLOAD_SVR_STAT_SUCC	"下載伺服器狀態成功！"
	#define U_DOWNLOAD_SVR_STAT_FAIL	"下載伺服器狀態失敗！"
	#define U_CONNECT_DOWNLOAD_SVR		"正在連接下載伺服器"
	#define U_TRY_UPDATE_SERVER			"正在嘗試在伺服器[%i]進行下載，請稍等..."
	#define U_TO_RESTART_SELF			"下載升級包成功，即將重新啟動升級程式..."
	#define U_NO_AVAILABLE_SERVER		"無可用的更新伺服器"
	#define U_FAILT_BUT_CAN_TRY			"更新失敗，您可以嘗試進入遊戲，但是可能會出現錯誤。"
	#define U_FAILT_BUT_CAN_TRY_2		"無可用的更新伺服器，您可以嘗試進入遊戲，但是可能會出現錯誤。"

	#define	U_DETAILHEADER_FILENAME		"檔案名稱"
	#define	U_DETAILHEADER_PROCESS		"進度"
	#define U_DETAILHEADER_STATUS		"狀態"
	#define U_DETAILHEADER_STATUS_COMPLETE	"完成"
	#define U_DETAILHEADER_STATUS_DOWNING	"正在下載"

	#define L_CONNECT_SERVER_SUCC		"連接下載伺服器成功"
	#define L_CANT_READ_DATA			"讀取不到數據"
	#define L_CANCEL_DOWNLOAD			"用戶取消下載"
	#define L_DOWN_AUTOUPDATE_SUCC		"下載升級程式成功"
	#define L_UPDAE_SUCC				"升級成功完成"


#endif //_AUTOUPDATE_K_STRING_TABLE_T_
