//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AutoUpdate.rc
//
#define IDS_ABOUTBOX                    1
#define IDS_CAPTION_VERSION_3           2
#define IDS_CAPTION_VERSION             3
#define IDC_EXMODE                      3 //<------EXVERSION
#define IDS_ERR_AUTOUPDATE_RUNNING      4
#define IDS_ERR_GAMEAPP_RUNNING         5
#define IDS_BTN_ENTER                   6
#define IDS_BTN_CANCEL                  7
#define IDS_BTN_RETRY                   8
#define IDS_SELECT_EDITION              9
#define IDS_STR_DEFAULTAPP              10
#define IDS_STRING_TOOOLDVERSION        11
#define IDS_STRING_RETRYING             12
#define IDS_STRING_QUITING              13
#define IDS_STRING_FATALERR             14
#define IDD_AUTOUPDATE_DIALOG           102
#define IDD_DIRSELECTDLG_DIALOG         103
#define IDD_DIALOGBAR                   104
#define IDR_MAINFRAME                   128
#define IDC_CUR_HAND                    131
#define IDR_JPEG_BACKGROUND_FS          133
#define IDB_BITMAP_PROGRESS_BLOCK       134
#define IDB_BITMAP_PROGRESS_BAR         135
#define IDB_BITMAP_RETRY_DISALBE        140
#define IDB_BITMAP_RETRY_DOWN           141
#define IDB_BITMAP_RETRY_OVER           142
#define IDB_BITMAP_RETRY_UP             143
#define IDB_BITMAP_CLOSE_UP             144
#define IDB_BITMAP_CLOSE_DISALBE        145
#define IDB_BITMAP_CLOSE_DOWN           146
#define IDB_BITMAP_CLOSE_OVER           147
#define IDB_BITMAP_SETTING_DISALBE      148
#define IDB_BITMAP_SETTING_DOWN         149
#define IDB_BITMAP_SETTING_OVER         150
#define IDB_BITMAP_SETTING_UP           151
#define IDB_BITMAP_PLAY_DISALBE         152
#define IDB_BITMAP_PLAY_DOWN            153
#define IDB_BITMAP_PLAY_OVER            154
#define IDB_BITMAP_PLAY_UP              155
#define IDB_BITMAP_BKPICTURE            156
#define IDB_BITMAP_MINCLOSE_OVER        157
#define IDB_BITMAP_MINCLOSE_DOWN        158
#define IDB_BITMAP_MINCLOSE_UP          159
#define IDB_BITMAP_MINIMIZE_UP          160
#define IDB_BITMAP_MINIMIZE_OVER        161
#define IDB_BITMAP_MINIMIZE_DOWN        162
#define IDB_BITMAP_SETTINGDLGBACKGROUND 164
#define IDB_BITMAP_MINCLOSE_DOW         165
#define IDI_ICON_DEFAULT                174
#define IDI_ICON_CANCEL                 175
#define IDI_ICON_OK                     176
#define IDI_ICON_OPEN                   177
#define IDI_ICON_UNCHECK                178
#define IDI_ICON_CHECK                  179
#define IDB_BITMAP_VERSIONSELECTBACKGROUD 180
#define IDR_MHT_DEFAULT                 181
#define IDD_DIALOG_CUSTOMDIALOG         182
#define IDB_BITMAP_CUSTOMMSGBACKGROUPD  183
#define IDD_DIALOG_DETAILINFO           184
#define IDB_BITMAP_DETAILINFOBACKGROUND 185
#define IDB_COLUMNHEADER_START          189
#define IDB_COLUMNHEADER_SPAN           190
#define IDB_COLUMNHEADER_END            191
#define IDC_CURSOR1                     192
#define IDB_BITMAP_DETAIL_UP            201
#define IDB_BITMAP_DETAIL_OVER          202
#define IDB_BITMAP_DETAIL_DOWN          203
#define IDB_BITMAP_DETAIL_DISABLE       204
#define IDB_BITMAP_MAINPROGRESSFRONT    205
#define IDB_BITMAP_MAINPROGRESSTHUMB    206
#define IDB_BITMAP_MAINPROGRESSBACK     207
#define IDB_BITMAP_FILEPROGRESSBACK     208
#define IDB_BITMAP_FILEPROGRESSFRONT    209
#define IDR_LEFTGIF                     214
#define IDD_GET_PATH                    215
#define IDB_FILE_TYPES                  218
#define IDB_BITMAP_BLOWERBK             228
#define IDR_BALL                        230
#define IDD_SEVERLIST                   232
#define IDD_ENTER_TIP                   233
#define IDB_UPDATE_TIP                  234
#define IDB_UPDATE_TIP2                 236
#define IDB_BUTTON_TIP_DISABLE          237
#define IDB_BUTTON_TIP_DOWN             238
#define IDB_BUTTON_TIP_OVER             239
#define IDB_BUTTON_TIP_UP               240
#define IDB_BITMAP_TREEBACK             241
#define IDB_BITMAP_SETTING_BAR          242
#define IDB_SETTING_BLOCK               243
#define IDD_SER_MODE_DIALOG             247 //<------EXVERSION
#define IDC_EXPLORER1                   1001
#define IDC_PROGRESS1                   1002
#define IDC_PROGRESS_OVERALLRATE        1002
#define IDC_PROGRESS2                   1003
#define IDC_PROGRESS_CURRENTRATE        1003
#define IDC_EDIT1                       1004
#define IDC_BTN_SETTING                 1005
#define IDC_BUTTON_MINICLOSE            1005
#define IDC_LIST_OK                     1005
#define IDC_UPDATE                      1006
#define IDC_LIST_CANCEL                 1008
#define IDC_BTN_PLAY                    1010
#define IDC_BTN_CLOSE                   1011
#define IDC_STATIC_PROGRESSMSG          1012
#define IDC_STATIC_OVERALLRATE          1013
#define IDC_STATIC_CURRENTRATE          1014
#define IDC_LIST1                       1018
#define IDC_LIST_STATUS                 1018
#define IDC_LIST                        1018
#define IDC_2DOption                    1019
#define IDC_BUTTON_MINIMIZE             1019
#define IDC_3DOption                    1020
#define IDC_BUTTON_CLOSE                1020
#define IDC_FullScreen                  1021
#define IDC_WindowOption                1022
#define IDC_DynaLightEnable             1024
#define IDC_OK                          1025
#define IDC_CANCEL                      1026
#define IDC_DEFAULT                     1027
#define IDC_STATIC_WARNINGINFO1         1029
//#define IDC_STATIC_WARNINGINFO2         1030
#define IDC_STATIC_TITLE                1031
#define IDC_STATIC_WINDOWMODETITLE      1036
#define IDC_STATIC_PICPATH              1037
#define IDC_STATIC_DESCRIPTION          1038
#define IDC_TXT_CAPPATH                 1039
//#define IDC_STATIC_INFO1                1039
#define IDC_BTN_CAPPATH                 1040
//#define IDC_STATIC_INFO2                1040
//#define IDC_STATIC_URL                  1041
//#define IDC_STATIC_INFO3                1042
#define IDC_LIST_DIR                    1043
#define IDC_TXT_DESCRIPTION             1044
#define IDC_BUTTON4                     1046
#define IDC_STATIC_MAINPROGRESS         1048
#define IDC_STATIC_FILEPROGRESS         1049
#define IDC_STATIC_LEFTGIF              1050
#define IDC_STATIC_BALL                 1050
#define IDC_TREE                        1051
#define IDC_STATIC_LEFTGIF2             1051
#define IDC_SCREEN800                   1052
#define IDC_SCREEN1024                  1053
#define IDC_SCREEN                      1054
#define IDC_TIP_OK                      1057
#define IDC_COMBO1                      1062
#define IDC_COMBO_IMAGE                 1062
#define IDC_STATIC_SOUND                1066
#define IDC_STATIC_MUSIC                1067
#define IDC_RICHEDIT1                   1074
#define IDC_RADIO2                      1077
#define IDC_800                         1077
#define IDC_RADIO4                      1079
#define IDC_1024                        1079
#define IDC_STATIC_FBL                  1080
#define ID_SELECT                       1081 //<------EXVERSION
#define IDC_NORMAL                      1082 //<------EXVERSION
#define IDC_BUTTON_EXCLOSE              1083
#define IDB_BITMAP_PITCH_ON             1085
#define IDB_BITMAP_PITCH_OFF            1087
#define IDC_STATIC_SHOWCAPTION          2017
#define IDB_BITMAP_EXSERVER_DOWN		2018
#define IDB_BITMAP_EXSERVER_OVER		2019
#define IDB_BITMAP_EXSERVER_UP			2020
#define IDB_BITMAP_NORMAL_DOWN			2021
#define IDB_BITMAP_NORMAL_OVER			2022
#define IDB_BITMAP_NORMAL_UP			2023
#define IDB_BITMAP_EX_BACKGROUNP	    2024

 // Next default values for new objects 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
