/************************************************************************
	filename: 	CEGUIPushButton.cpp
	created:	13/4/2004
	author:		Paul D Turner
	
	purpose:	Implementation of PushButton widget base class
*************************************************************************/
/*************************************************************************
    Crazy Eddie's GUI System (http://www.cegui.org.uk)
    Copyright (C)2004 - 2005 Paul D Turner (paul@cegui.org.uk)

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*************************************************************************/
#include "elements/CEGUIPushButton.h"

// Start of CEGUI namespace section
namespace CEGUI
{

/*************************************************************************
	constants
*************************************************************************/
// properties
PushButtonProperties::NormalImage PushButton::d_normalImageProperty;
PushButtonProperties::PushedImage PushButton::d_pushedImageProperty;
PushButtonProperties::HoverImage  PushButton::d_hoverImageProperty;
PushButtonProperties::DisabledImage  PushButton::d_disabledImageProperty;
PushButtonProperties::TextXOffset PushButton::d_textXOffsetProperty;


/*************************************************************************
	Constructor
*************************************************************************/
PushButton::PushButton(const String& type, const String& name) :
	ButtonBase(type, name)
{
    d_textXOffset = 0.0f;

	d_normalImage	= NULL;	
	d_hoverImage	= NULL;	
	d_pushedImage	= NULL;	
	d_disabledImage = NULL;

	// add the additional events generated by this derived class
	addPushButtonEvents();

    // add properties for push button class
    addPushButtonProperties();
}


/*************************************************************************
	Destructor
*************************************************************************/
PushButton::~PushButton(void)
{
}

const Image* PushButton::getNormalImage(void) const
{
    return d_normalImage;
}

const Image* PushButton::getHoverImage(void) const
{
    return d_hoverImage;
}

const Image* PushButton::getPushedImage(void) const
{
    return d_pushedImage;
}

const Image* PushButton::getDisabledImage(void) const
{
    return d_disabledImage;
}

float PushButton::getTextXOffset(void) const
{
    return d_textXOffset;
}

void PushButton::setNormalImage(const Image* image)
{
	d_normalImage = image;
    requestRedraw();
}

void PushButton::setHoverImage(const Image* image)
{
	d_hoverImage = image;
    requestRedraw();
}

void PushButton::setPushedImage(const Image* image)
{
	d_pushedImage = image;
    requestRedraw();
}

void PushButton::setDisabledImage(const Image* image)
{
    d_disabledImage = image;
    requestRedraw();
}

void PushButton::setTextXOffset(float offset)
{
    d_textXOffset = offset;
}

/*************************************************************************
	Add button specific events	
*************************************************************************/
void PushButton::addPushButtonEvents(void)
{
	addEvent(EventClicked);
}


/*************************************************************************
	handler invoked internally when the button is clicked.	
*************************************************************************/
void PushButton::onClicked(WindowEventArgs& e)
{
	fireEvent(EventClicked, e);
}


/*************************************************************************
	Handler for mouse button release events
*************************************************************************/
void PushButton::onMouseButtonUp(MouseEventArgs& e)
{
	if ((e.button == LeftButton) && isPushed())
	{
		Window* sheet = getRoot();

		if (sheet != NULL)
		{
			// if mouse was released over this widget
			if (this == sheet->getChildAtPosition(e.position))
			{
				// fire event
				WindowEventArgs args(this);
				onClicked(args);
			}
		}

		e.handled = true;
	}

	// default handling
	ButtonBase::onMouseButtonUp(e);
}

void PushButton::onSized(WindowEventArgs& e)
{
    // default processing
    ButtonBase::onSized(e);
}

void PushButton::addPushButtonProperties(void)
{
    addProperty(&d_normalImageProperty);
    addProperty(&d_pushedImageProperty);
    addProperty(&d_hoverImageProperty);
    addProperty(&d_disabledImageProperty);
    addProperty(&d_textXOffsetProperty);
}

} // End of  CEGUI namespace section
